### ISSUE TITLE
Logo Design Work: TypeRig

### ISSUE THREAD

**Issue by baranpirincal** [kateliev/TypeRig#13]
Hey, I can make a logo design for TypeRig. If you interested we can talk about design decisions. By the way, my purpose is supporting open source project in field of graphics. I am waiting your feedback. Have a nice day! :)

Best Regards,
Baran Pirincal
Visual Communication Designer

**Comment by kateliev** [comment]
Thank you Baran, but at this point the TypeRig project does not need a logo.
