### ISSUE TITLE
Cannot size window down

### ISSUE THREAD

**Issue by hyvyys** [kateliev/TypeRig#19]
https://recordit.co/0RBuGsmNXB

If I maximize the window, the tab ribbon on the right side becomes scrolled. But if I want to resize the window height down in non maximized mode, it's not possible.

Preferably the tab buttons could be displayed horizontally, with wrapping enabled.

**Comment by kateliev** [comment]
Solved!

**Comment by twardoch** [comment]
TR panels are now more space-efficient on macOS
