### ISSUE TITLE
How to run a script across multiple glyphs?

### ISSUE THREAD

**Issue by Wirdek** [kateliev/TypeRig#39]
Hello Vassil,
how do I run a Fontlab script, in the way it modify several selected glyphs at once? 
So far it seems to affect just the one "current/active", lastly selected glyph only, even when multiple glyphs are selected in "Font tab" window.

Otherwise, this script was was kindly provided by you - thanks again, it has helped me a lot!  :)

#FLM: Sort Contours
from typerig.proxy import pFont, pGlyph
sort_by_y = True # Put False here if you want them to be X sorted
glyph = pGlyph()
for shape in glyph.shapes():
 shape.contours = sorted(shape.contours, key=lambda c:c.bounds[sort_by_y])
glyph.updateObject(glyph.fl)

Note: I'm no expert in scripting.
Please help,
Vit

**Comment by kateliev** [comment]
Hi, thank you for your patience... Below is the code for multiple selected glyphs in Glyph Window

```
#FLM: Sort Contours Multiple Glyphs
from typerig.proxy import pFont, pGlyph

# - Init
sort_by_y = True  # Put False here if you want them to be X sorted
font = pFont()

# - Process
for glyph in font.selected_pGlyphs():
	for shape in glyph.shapes():
		shape.contours = sorted(shape.contours, key=lambda c:c.bounds[sort_by_y])
		print 'DONE:\t Sorting contours for glyph: %s'%glyph.name

font.update()
```

**Comment by Wirdek** [comment]
Thank you very much, Vassil 👍

**Comment by kateliev** [comment]
@Wirdek This is now part of the **Standard suite** - TypeRig Panel > Contour Sub-panel !

![image](https://user-images.githubusercontent.com/10247582/88591461-0dcc7980-d065-11ea-9915-5450af2fd876.png)
Works as usual on all layers and glyphs chosen in TR Masthead. Shift + Click will reverse operation.
Enjoy!

PS: You have to update TR and check if your Contour sub-panel is bumped up to ver 0.25.

**Comment by Wirdek** [comment]
Great work, Vassil,
I'm on vacations right now, but I will check it asap!

I'm really a beginner at scipting (a way more a user than a coder), but I can see the huge potential - is there any educational area around you would recommend?

How about eg. the scripts that has worked back in FL5? Is there a way to use them again?
(to be honest I haven't tried it yet - I'm just at the stage to get used to working with with FL7 so far :)

Cheers,
(v)
