### ISSUE TITLE
Correct Connetions

### ISSUE THREAD

**Issue by Wirdek** [kateliev/TypeRig#44]
Hello,
there was this feature back in FL5 - copy from manual:
**Contour > Correct Connections** _to automatically fix incorrect sharp connections, that is sharp connections that can be turned into smooth connections without any change in the shape of the contour._

This is exactly what I need to do now, but I cannot find anything like that in FL7 - is there perhaps such a feature in the Typerig somewhere?

I don't wan any other Clean-up/Harmonize/Blance - just this simple task - please see attached (correct on top)
![image](https://user-images.githubusercontent.com/68431285/93870992-45a31680-fcce-11ea-90b8-781870590eee.png)

**Comment by twardoch** [comment]
Contour > Node > Detect Smooth, also in Actions > Contour > Detect nodes

**Comment by Wirdek** [comment]
Excellent - thanks! :)

**Comment by Wirdek** [comment]
Hello Adam,
it indeed seems to do the same thing as "correct connections" did, but for some reason it is now working in some cases:

![Detect Smooth](https://user-images.githubusercontent.com/68431285/93996292-5e750000-fd92-11ea-8d41-92c3a0cc4160.png)

It corrects the bigger Circle, but smaller Teminals are unfortunatelly intact.
I dont know - what might be the problem?
(connections are smooth, coordinates rounded - i see no reason for this)

Do you have any suggestions?

I'm sending a sample from my font attached.
[Unnamed-Regular.zip](https://github.com/kateliev/TypeRig/files/5267180/Unnamed-Regular.zip)

Please help,

**Comment by kateliev** [comment]
Yes! It seems you are right - FL seems to not detect smooth nodes as such below a certain threshold (@twardoch ?). Scaling the outlines (lets say x2) and then running the command detects the smooth nodes without problems. 

The same goes for FL Py API. Running _flNode().canBeSmooth()_ results False under same conditions. Doubling the size fixes is. Also _FontGate's fgShape().autoSmooth()_ and _fgContour().autoSmooth()_ behave the same. 

So my best guess presume it is in-built into the app to behave in such a way. So there is no... "easy" fix for now. As i see it there are two ways of handling the issue besides reporting it as problem to FL team:
1) A "hacky" solution to use python to scale the outline, detect the smooth nodes and scale it back;
2) True pythonic math solution to detect which nodes could be smooth.

...regretfully I cannot spend time on any of those solutions, but will inform you when i arrive at (2) while working on TR Core Node object in the coming months (as planned) - meaning I know a solution and the right code to do it but i do not have the time....

_Interesting design btw!_

**Comment by Wirdek** [comment]
Hello Vassil,
I'll forward your info to FL team.

Thanks for your time!


Logo
Vít Šmejkal  |  graphic design
a: Dvouletky 2689/143 | 100 00 Praha 10
Prague | Czech Republic
e:vit@vtypo.com |w: www.vtypo.com
m:+420 777 053 340

------ Původní zpráva ------
Od: "Vassil Kateliev" <notifications@github.com>
Komu: "kateliev/TypeRig" <TypeRig@noreply.github.com>
Kopie: "Wirdek" <vit.smejkal@gmail.com>; "Author" 
<author@noreply.github.com>
Odesláno: 24.09.2020 12:40:59
Předmět: Re: [kateliev/TypeRig] Correct Connetions (#44)


Yes! It seems you are right - FL seems to not detect smooth nodes as 
such below a certain threshold (@twardoch <https://github.com/twardoch> 
?). Scaling the outlines (lets say x2) and then running the command 
detects the smooth nodes without problems.

The same goes for FL Py API. Running flNode().canBeSmooth() results 
False under same conditions. Doubling the size fixes is. Also FontGate's 
fgShape().autoSmooth() and fgContour().autoSmooth() behave the same.

So my best guess presume it is in-built into the app to behave in such a 
way. So there is no... "easy" fix for now. As i see it there are two 
ways of handling the issue besides reporting it as problem to FL team:

A "hacky" solution to use python to scale the outline, detect the smooth 
nodes and scale it back;True pythonic math solution to detect which 
nodes could be smooth.
...regretfully I cannot spend time on any of those solutions, but will 
inform you when i arrive at (2) while working on TR Core Node object in 
the coming months (as planned) - meaning I know a solution and the right 
code to do it but i do not have the time....

Interesting design btw!

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub 
<https://github.com/kateliev/TypeRig/issues/44#issuecomment-698264705>, 
or unsubscribe
