### ISSUE TITLE
Cannot import name QtGui

### ISSUE THREAD

**Issue by hyvyys** [kateliev/TypeRig#46]
For a while, I am unable to open TypeRig Panel, I get the following error:

```
Traceback (most recent call last):
  File "C:/Users/Adam/Documents/FontLab/FontLab 7/Scripts/TypeRig GUI/typerig-panel.py", line 24, in <module>
    import Panel 
  File "C:/Users/Adam/Documents/FontLab/FontLab 7/Scripts/TypeRig GUI\Panel\__init__.py", line 19, in <module>
    __import__(module, locals(), globals())
  File "C:/Users/Adam/Documents/FontLab/FontLab 7/Scripts/TypeRig GUI\Panel\String.py", line 38, in <module>
    from typerig import QtGui
ImportError: cannot import name QtGui
```

Lacking a better idea, and having noticed that a script that does work for me (Metrics) imports from `typerig.gui` and not `typerig`, I changed `from typerig import QtGui` to `from typerig.gui import QtGui`, then I got

```
Traceback (most recent call last):
  File "C:/Users/Adam/Documents/FontLab/FontLab 7/Scripts/TypeRig GUI/typerig-panel.py", line 24, in <module>
    import Panel 
  File "C:/Users/Adam/Documents/FontLab/FontLab 7/Scripts/TypeRig GUI\Panel\__init__.py", line 19, in <module>
    __import__(module, locals(), globals())
  File "C:/Users/Adam/Documents/FontLab/FontLab 7/Scripts/TypeRig GUI\Panel\String.py", line 40, in <module>
    from typerig.string import stringGen, stringGenPairs, strRepDict, fillerList, baseGlyphset
ImportError: No module named string
```

I'm on Windows btw.

**Comment by twardoch** [comment]
Somehow I feel you have possibly two different typerig modules. How did you install TR?

**Comment by hyvyys** [comment]
Most certainly. I installed it via FL's Install Scripts command. Note though that I have several beta versions of FL installed. I thought that might be the issue, so I installed the latest beta again but used the default directory this time and even allowed FL to install python (I normally uncheck that since I already have python(s)). To no avail.

**Comment by twardoch** [comment]
Try

```
import typerig
print(typerig.__file__)
```

or

```
import os
import inspect
import typerig 
print(os.path.dirname(inspect.getfile(typerig)))
```

**Comment by kateliev** [comment]
Nope, this is due to TR installation being too old! The **String.py** sub-panel has been moved to a new folder at least three months ago. Please update your TR installation to the latest version. Had similar issues with other users about missing sub-panels and modules. It seems all of them have installed TR in time when something has been changed or some code refactored...

**Comment by hyvyys** [comment]
Mystery solved.

The install script writes to `C:\Users\Adam\Documents\FontLab\FontLab 7\python\2.7\site-packages\typerig` but it seems FontLab uses the python installed globally in the system, copying typerig to `C:\Python27\Lib\site-packages` allowed Typerig Panel to run.

How does FontLab itself know which python to use and when? The installator wants to overwrite what appears to be the global installation (does it write to PATH too?) and know I learn there's another copy in Documents. I'd like a bit more transparency and consistency here.
