### ISSUE TITLE
pFont.familyName incorrect

### ISSUE THREAD

**Issue by hyvyys** [kateliev/TypeRig#48]
```
from typerig.proxy import pFont

font = pFont()
print font.familyName
```

The above actually prints full name (family + style) of the last master. (Unless it's supposed to return the Style Group Name and it's correct?)

For anyone looking here, `font.fl.tfn` returns what I'm after.

**Comment by kateliev** [comment]
Thank you @hyvyys , but I cannot confirm that...
'pFont.familyName' is proxy of 'fgFontInfo.familyName' and is working as expected...
![image](https://user-images.githubusercontent.com/10247582/104109446-9e76d900-52d6-11eb-95cf-db72570386e0.png)

after some tests...
- I cannot confirm your statement that it returns family + style. Please look below.
- If there is an error it is on the FL side or in your particular version of FL (but i doubt it)
- You could have a naming issue of some sort?

![image](https://user-images.githubusercontent.com/10247582/104109457-ccf4b400-52d6-11eb-9c84-633b495a45f4.png)

**Comment by kateliev** [comment]
Pushed, fixed :)
