### ISSUE TITLE
Installing error

### ISSUE THREAD

**Issue by JonathanBartley** [kateliev/TypeRig#53]
After I drag the Install.vfpy into fontLab 7 it gives me this error:
IOError: [Errno 13] Permission denied: '/Library/Python/2.7/site-packages/typerig.pth'

How can I fix this?

**Comment by kateliev** [comment]
Hi @JonathanBartley, sorry for my delayed response. Please take a look at this thread over Fontlab forum. It might see irrelevant but actually explains a lot about installation + the new installer that i pushed yesterday.

**Comment by JonathanBartley** [comment]
Thank you, I already resolved it.
