### ISSUE TITLE
Cannot even install

### ISSUE THREAD

**Issue by cssobral2013** [kateliev/TypeRig#55]
It hangs into an empty CMD for a while, then displays the following error: "File https://codeload.github.com/kateliev/TypeRig/zip/master is not accessible", despite I'm having a working connection (or else
I'd even not be able to access this Github). However, directly accessing this link opens it as normal.

The output displays the following (at the moment the install stops):

copying src\pyclipper\__init__.py -> build\lib.win32-2.7\pyclipper
  running build_ext
  building 'pyclipper._pyclipper' extension
  error: Microsoft Visual C++ 9.0 is required. Get it from http://aka.ms/vcpython27
  ----------------------------------------
  ERROR: Failed building wheel for pyclipper
ERROR: Could not build wheels for pyclipper which use PEP 517 and cannot be installed directly
WARNING: You are using pip version 19.2.3, however version 20.3.4 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

[INFO] Installation of Python packages completed. Check Output panel for details.
Traceback (most recent call last):
  File "D:/Luiz Sobral/Documents/FontLab/FontLab 7/Scripts/update-install.py", line 78, in handleResponse
    self.fnc(self.downout, self.downerr, self.url)
  File "D:/Luiz Sobral/Documents/FontLab/FontLab 7/Scripts/update-install.py", line 230, in download_typerig
    ok = install_typerig_finish(zip, udf)
UnboundLocalError: local variable 'udf' referenced before assignment

**Comment by kateliev** [comment]
Hi @cssobral2013 i am sorry to hear that you are experiencing problems installing TypeRig (TR). Regretfully the FontLab (FL) provided installer fails in some way. Perhaps @twardoch could help with that?! About the error you are having - I find it pretty strange, as PyClipper is not used in any way in TR. I have no such dependency.

For installing TR i would suggest installing manually from this repository. Just download the package, unzip it somewhere. Run install.py with sufficient privileges and then after completing, just point FL towards the GUI scripts folders. Also please note what kind of Python installation you are using. If you are using FL internal Python installation, then it would be better to just manually copy the /Typerig folder residing in /lib to where FL keeps its python site packages...

**Comment by cssobral2013** [comment]
@kateliev - Is it on C:\Program Files (x86)\Fontlab\FontLab 7\Resources\python\2.7\site-packages (I'm using 32-bit FontLab)?

**Comment by twardoch** [comment]
That installer installs a few more packages but it seems one of them requires compiled packages which in turn require a compiler. I'm sorry about that. We'll need to do it differently.
