### ISSUE TITLE
Cannot import name pFont

### ISSUE THREAD

**Issue by hyvyys** [kateliev/TypeRig#56]
Fresh Windows & FontLab 7 installation, installed TypeRig via Scripts > Update/Install, restarted, and failed to run a script:

```py
from typerig.proxy import pFont
```

```
cannot import name pFont
```

What am I missing?

**Comment by hyvyys** [comment]
Hi @kateliev, I installed the latest version from this repo, and modified my script to the following:

```py
from typerig.proxy.fl.font import pFont
```
Now I get this error:

```
No module named font (line 5): 
Traceback (most recent call last):
  File "<string>", line 5, in <module>
ImportError: No module named font
```

**Comment by hyvyys** [comment]
```py
from typerig.proxy.fl.objects.font import pFont
```

This worked for me instead.

**Comment by kateliev** [comment]
@hyvyys Yes this is the correct way to do it! Sorry for dropping a word in the suggested solution above!

**Comment by StefanPeev** [comment]
@kateliev **Report of an error in Delta Machine**

Traceback (most recent call last):
  File "C:/Users/Context/Documents/FontLab/FontLab 7/Scripts/Delta Machine/DeltaMachine.py", line 26, in <module>
    from typerig.proxy.fl.objects.font import pFont
  File "C:\Users\Context\Documents\FontLab\FontLab 7\python\2.7\site-packages\typerig\proxy\fl\objects\font.py", line 24, in <module>
    from typerig.proxy.fl.objects.glyph import pGlyph, eGlyph
  File "C:\Users\Context\Documents\FontLab\FontLab 7\python\2.7\site-packages\typerig\proxy\fl\objects\glyph.py", line 21, in <module>
    from fontlab_private.fontTools.pens import statisticsPen
ImportError: No module named fontlab_private.fontTools.pens

**Comment by twardoch** [comment]
@kateliev A safe backwards- and future-compatible fix for this would be: 

```
try: 
  from fontlab_private.fontTools.pens import statisticsPen
except ImportError:
  from fontTools.pens import statisticsPen
```

**Comment by twardoch** [comment]
(And similar in the other portions that use fontTools)

**Comment by twardoch** [comment]
Alternatively, you (@kateliev ) might create your own slim proxy for some fontTools objects that does this try/except importing, and in your real code just import that

**Comment by twardoch** [comment]
@StefanPeev TypeRig is now updated on https://github.com/kateliev/TypeRig
