### ISSUE TITLE
pGlyph > Mask Issue

### ISSUE THREAD

**Issue by alex-phil** [kateliev/TypeRig#63]
Vassil, please take a look at the following lines:

https://github.com/kateliev/TypeRig/blob/3fbab884eb8ac28e69440dfe7249f65f543ee0bd/Lib/typerig/proxy/fl/objects/glyph.py#L266-L267

Suppose you have a glyph with layers **Regular** and **mask.Regular** having layer indices 1 and 0 respectively. Then you will see that
```
pGlyph().mask(layer=0)
```
refers to the **Regular** layer and not to **mask.Regular**. More generally, if the layer index of a mask layer is used as the value of the keyword argument **layer**, the function will yield the parent layer of the mask layer, not the mask layer itself. But that is probably not intended, as the description of your function says “Returns mask layer no matter the reference.”
  
To quickly check the behavior of the function in the described situation:
```
from typerig.proxy.fl.objects.glyph import *
print(pGlyph().mask(layer=0).name)
```
Thank you for taking a look.

**Comment by kateliev** [comment]
@alex-phil i guess you are right, but it it a bit more complicated on philosophical level.... I fixed it in the most basic manner, always returning the mask layer by checking if the layer retrieved by indexing is actually the needed mask layer itself and if so it is returned. 
```python
if isinstance(layer, int):
  return_layer = self.fl.layers[layer]
  return return_layer if return_layer.isMaskLayer() else return_layer.getMaskLayer(force_create)
```

**Comment by kateliev** [comment]
If that is the desired solution, please close the issue :)

**Comment by alex-phil** [comment]
It’s almost perfect, Vassil. In the following line

https://github.com/kateliev/TypeRig/blob/a7e804b5309d8526b0a9fc16a0f7d4bd1944dfe7/Lib/typerig/proxy/fl/objects/glyph.py#L271

you will just have to remove the function parentheses after **isMaskLayer** and you should be done.

```
return return_layer if return_layer.isMaskLayer else return_layer.getMaskLayer(force_create)
```

**Comment by kateliev** [comment]
Done!
