### ISSUE TITLE
Error running Delta Machine

### ISSUE THREAD

**Issue by insignedesign** [kateliev/TypeRig#71]
When running Delta Machine on FL8 with Windows/Python 3.10 I get the following error.

Traceback (most recent call last):
  File "C:/Users/jdool/OneDrive/Documents/FontLab/FontLab 8/Scripts/Delta Machine/DeltaMachine.py", line 28, in <module>
    from typerig.proxy.fl.gui.widgets import getProcessGlyphs, TRSliderCtrl, TRMsgSimple
ImportError: cannot import name 'TRMsgSimple' from 'typerig.proxy.fl.gui.widgets' (C:\Users\jdool\AppData\Roaming\Python\Python310-32\site-packages\typerig\proxy\fl\gui\widgets.py)
Traceback (most recent call last):
  File "C:/Users/jdool/OneDrive/Documents/FontLab/FontLab 8/Scripts/Delta Machine/DeltaMachine.py", line 28, in <module>
    from typerig.proxy.fl.gui.widgets import getProcessGlyphs, TRSliderCtrl, TRMsgSimple
ImportError: cannot import name 'TRMsgSimple' from 'typerig.proxy.fl.gui.widgets' (C:\Users\jdool\AppData\Roaming\Python\Python310-32\site-packages\typerig\proxy\fl\gui\widgets.py)

Any suggestions?

**Comment by kateliev** [comment]
Hi @insignedesign , this has been addressed couple of weeks ago. Please update your TR to the very latest and let me know if it works!

**Comment by insignedesign** [comment]
Thank you, I got this working on my PC. Now, If I can only do the same for my mac with FL8.

Thanks for all you do,
