### ISSUE TITLE
Little Rename Anchors Script Bug

### ISSUE THREAD

**Issue by alex-phil** [kateliev/TypeRig#83]
Hi Vassil,

the following line gives me an error:

https://github.com/kateliev/TypeRig/blob/18e80c0fc7aee4eec0bee034d5b18d5ff16c3192/Scripts/TypeRig%20Tools/TR-RenameAnchors.py#L144

And this is because **process_glyphs** is a set: 

https://github.com/kateliev/TypeRig/blob/18e80c0fc7aee4eec0bee034d5b18d5ff16c3192/Scripts/TypeRig%20Tools/TR-RenameAnchors.py#L130

So you will have to replace **process_glyphs** in line 144 by **len(process_glyphs)** — or simply use **if process_glyphs:** in order to check whether the set is empty. Does that make sense? :)

**Comment by kateliev** [comment]
@alex-phil you are totally right! Thank you!
